namespace RASLogAggregator.Services;

/// <summary>
/// Localisation FR / EN / DE. Toutes les chaînes visibles passent par Loc.T / Loc.F.
/// Repli automatique sur l'anglais si une clé manque dans la langue courante.
/// </summary>
public static class Loc
{
    public static string Lang { get; set; } = "en";

    public static string T(string key)
    {
        var d = Lang switch { "fr" => FR, "de" => DE, _ => EN };
        if (d.TryGetValue(key, out var v)) return v;
        return EN.TryGetValue(key, out var e) ? e : key;
    }

    public static string F(string key, params object[] args) => string.Format(T(key), args);

    private static readonly Dictionary<string, string> FR = new()
    {
        ["about_title"] = "À propos",
        ["about_dev"] = "Développé par",
        ["about_ai"] = "Conçu et développé avec l'assistance de Claude Fable 5 (Anthropic) — de l'architecture au design de l'interface.",
        ["about_close"] = "Fermer",
        ["tip_about"] = "À propos de FarmScope",
        ["app_subtitle"] = "logs agrégés de la ferme RAS",
        ["btn_connect"] = "Connexion / Découverte",
        ["btn_refresh"] = "↻ Rafraîchir",
        ["btn_export"] = "Exporter CSV",
        ["lbl_search"] = "Recherche :",
        ["lbl_role"] = "Rôle :",
        ["lbl_server"] = "Serveur :",
        ["lbl_file"] = "Fichier :",
        ["filter_all"] = "(tous)",
        ["sev_other"] = "Autre",
        ["col_time"] = "Horodatage",
        ["col_sev"] = "Sév.",
        ["col_role"] = "Rôle",
        ["col_server"] = "Serveur",
        ["col_file"] = "Fichier",
        ["col_msg"] = "Message",
        ["tip_theme"] = "Basculer thème clair / sombre",
        ["st_ready"] = "Prêt.",
        ["st_discovering"] = "Découverte de la ferme via {0}…",
        ["st_no_components"] = "Aucun composant retourné par l'API RAS. Vérifie le compte/serveur.",
        ["st_found"] = "{0} composant(s) découvert(s). Lecture des logs…",
        ["st_disc_fail"] = "Échec de la découverte.",
        ["st_reading"] = "Lecture des logs…",
        ["st_reading_file"] = "Lecture {0} / {1} …",
        ["st_done"] = "{0} entrées · {1} fichier(s) lus",
        ["st_done_err"] = " — {0} fichier(s) en erreur",
        ["st_read_fail"] = "Échec de la lecture des logs.",
        ["st_export"] = "Export : {0}",
        ["st_count"] = "{0} / {1} entrées affichées",
        ["mb_disc_title"] = "Erreur de découverte RAS",
        ["mb_read_title"] = "Erreur de lecture",
        ["err_unreachable"] = "serveur injoignable (SMB/445)",
        ["err_timeout"] = "timeout (>8 s, accès bloqué)",
        ["cw_title"] = "FarmScope — connexion à la ferme",
        ["cw_heading"] = "Découverte via l'API PowerShell RAS",
        ["cw_sub"] = "Renseigne un Connection Broker / Publishing Agent et un compte admin RAS.",
        ["cw_server"] = "Serveur (FQDN du Broker)",
        ["cw_user"] = "Utilisateur admin RAS (DOMAINE\\user)",
        ["cw_pass"] = "Mot de passe",
        ["cw_altcreds"] = "Identifiants Windows différents pour les partages C$",
        ["cw_share_user"] = "User (partages)",
        ["cw_share_pass"] = "Mot de passe (partages)",
        ["cw_cancel"] = "Annuler",
        ["cw_connect"] = "Connexion",
        ["mb_fields_title"] = "Champs manquants",
        ["mb_fields_body"] = "Serveur, utilisateur et mot de passe sont requis.",
    };

    private static readonly Dictionary<string, string> EN = new()
    {
        ["about_title"] = "About",
        ["about_dev"] = "Developed by",
        ["about_ai"] = "Designed and built with the assistance of Claude Fable 5 (Anthropic) — from architecture to UI design.",
        ["about_close"] = "Close",
        ["tip_about"] = "About FarmScope",
        ["app_subtitle"] = "aggregated RAS farm logs",
        ["btn_connect"] = "Connect / Discover",
        ["btn_refresh"] = "↻ Refresh",
        ["btn_export"] = "Export CSV",
        ["lbl_search"] = "Search:",
        ["lbl_role"] = "Role:",
        ["lbl_server"] = "Server:",
        ["lbl_file"] = "File:",
        ["filter_all"] = "(all)",
        ["sev_other"] = "Other",
        ["col_time"] = "Timestamp",
        ["col_sev"] = "Sev.",
        ["col_role"] = "Role",
        ["col_server"] = "Server",
        ["col_file"] = "File",
        ["col_msg"] = "Message",
        ["tip_theme"] = "Toggle light / dark theme",
        ["st_ready"] = "Ready.",
        ["st_discovering"] = "Discovering farm via {0}…",
        ["st_no_components"] = "No components returned by the RAS API. Check account/server.",
        ["st_found"] = "{0} component(s) discovered. Reading logs…",
        ["st_disc_fail"] = "Discovery failed.",
        ["st_reading"] = "Reading logs…",
        ["st_reading_file"] = "Reading {0} / {1} …",
        ["st_done"] = "{0} entries · {1} file(s) read",
        ["st_done_err"] = " — {0} file(s) failed",
        ["st_read_fail"] = "Failed to read logs.",
        ["st_export"] = "Exported: {0}",
        ["st_count"] = "{0} / {1} entries shown",
        ["mb_disc_title"] = "RAS discovery error",
        ["mb_read_title"] = "Read error",
        ["err_unreachable"] = "server unreachable (SMB/445)",
        ["err_timeout"] = "timeout (>8 s, blocked access)",
        ["cw_title"] = "FarmScope — connect to farm",
        ["cw_heading"] = "Discovery via the RAS PowerShell API",
        ["cw_sub"] = "Enter a Connection Broker / Publishing Agent and a RAS admin account.",
        ["cw_server"] = "Server (Broker FQDN)",
        ["cw_user"] = "RAS admin user (DOMAIN\\user)",
        ["cw_pass"] = "Password",
        ["cw_altcreds"] = "Different Windows credentials for C$ shares",
        ["cw_share_user"] = "User (shares)",
        ["cw_share_pass"] = "Password (shares)",
        ["cw_cancel"] = "Cancel",
        ["cw_connect"] = "Connect",
        ["mb_fields_title"] = "Missing fields",
        ["mb_fields_body"] = "Server, user and password are required.",
    };

    private static readonly Dictionary<string, string> DE = new()
    {
        ["about_title"] = "Über",
        ["about_dev"] = "Entwickelt von",
        ["about_ai"] = "Entworfen und entwickelt mit Unterstützung von Claude Fable 5 (Anthropic) — von der Architektur bis zum UI-Design.",
        ["about_close"] = "Schließen",
        ["tip_about"] = "Über FarmScope",
        ["app_subtitle"] = "aggregierte RAS-Farm-Logs",
        ["btn_connect"] = "Verbinden / Erkennen",
        ["btn_refresh"] = "↻ Aktualisieren",
        ["btn_export"] = "CSV exportieren",
        ["lbl_search"] = "Suche:",
        ["lbl_role"] = "Rolle:",
        ["lbl_server"] = "Server:",
        ["lbl_file"] = "Datei:",
        ["filter_all"] = "(alle)",
        ["sev_other"] = "Andere",
        ["col_time"] = "Zeitstempel",
        ["col_sev"] = "Schw.",
        ["col_role"] = "Rolle",
        ["col_server"] = "Server",
        ["col_file"] = "Datei",
        ["col_msg"] = "Meldung",
        ["tip_theme"] = "Helles / dunkles Design umschalten",
        ["st_ready"] = "Bereit.",
        ["st_discovering"] = "Farm-Erkennung über {0}…",
        ["st_no_components"] = "Keine Komponenten von der RAS-API zurückgegeben. Konto/Server prüfen.",
        ["st_found"] = "{0} Komponente(n) erkannt. Logs werden gelesen…",
        ["st_disc_fail"] = "Erkennung fehlgeschlagen.",
        ["st_reading"] = "Logs werden gelesen…",
        ["st_reading_file"] = "Lese {0} / {1} …",
        ["st_done"] = "{0} Einträge · {1} Datei(en) gelesen",
        ["st_done_err"] = " — {0} Datei(en) fehlgeschlagen",
        ["st_read_fail"] = "Lesen der Logs fehlgeschlagen.",
        ["st_export"] = "Exportiert: {0}",
        ["st_count"] = "{0} / {1} Einträge angezeigt",
        ["mb_disc_title"] = "RAS-Erkennungsfehler",
        ["mb_read_title"] = "Lesefehler",
        ["err_unreachable"] = "Server nicht erreichbar (SMB/445)",
        ["err_timeout"] = "Timeout (>8 s, Zugriff blockiert)",
        ["cw_title"] = "FarmScope — mit Farm verbinden",
        ["cw_heading"] = "Erkennung über die RAS-PowerShell-API",
        ["cw_sub"] = "Connection Broker / Publishing Agent und ein RAS-Admin-Konto angeben.",
        ["cw_server"] = "Server (Broker-FQDN)",
        ["cw_user"] = "RAS-Admin-Benutzer (DOMÄNE\\user)",
        ["cw_pass"] = "Passwort",
        ["cw_altcreds"] = "Andere Windows-Anmeldedaten für C$-Freigaben",
        ["cw_share_user"] = "Benutzer (Freigaben)",
        ["cw_share_pass"] = "Passwort (Freigaben)",
        ["cw_cancel"] = "Abbrechen",
        ["cw_connect"] = "Verbinden",
        ["mb_fields_title"] = "Fehlende Felder",
        ["mb_fields_body"] = "Server, Benutzer und Passwort sind erforderlich.",
    };
}
